version: 2
project_name: terraform-provider-vtm

builds:
  - id: v8.3
    main: ./8.3
    binary: "{{ .ProjectName }}_v{{ .Version }}"
    goos: [freebsd, windows, linux, darwin]
    goarch: [amd64, arm64]
    env: [CGO_ENABLED=0]
    flags: [-mod=vendor]
    ldflags: ["-s", "-w", "-X main.version={{.Version}}", "-X main.commit={{.Commit}}"]

archives:
  - id: default
    formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - RELEASE_NOTES.txt

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  use: github-native
